In [1]:
!pip install transformers==2.8.0

     |████████████████████████████████| 573kB 3.5MB/s 
     |████████████████████████████████| 1.1MB 16.1MB/s 
     |████████████████████████████████| 3.7MB 19.3MB/s 
     |████████████████████████████████| 890kB 43.0MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893260 sha256=431672583c64cd1e21d8c037e81864cd0d9e6e99407822b4358fb98baa4307cd
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


In [2]:
!wget https://raw.githubusercontent.com/huggingface/transformers/v2.8.0/examples/run_language_modeling.py

--2020-05-20 09:48:00--  https://raw.githubusercontent.com/huggingface/transformers/v2.8.0/examples/run_language_modeling.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 34328 (34K) [text/plain]
Saving to: ‘run_language_modeling.py’

run_language_modeli 100%[===================>]  33.52K  --.-KB/s    in 0.01s   

2020-05-20 09:48:00 (3.06 MB/s) - ‘run_language_modeling.py’ saved [34328/34328]



In [3]:
!wget https://s3.amazonaws.com/research.metamind.io/wikitext/wikitext-2-v1.zip
!unzip wikitext-2-v1.zip

--2020-05-20 09:48:02--  https://s3.amazonaws.com/research.metamind.io/wikitext/wikitext-2-v1.zip
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.217.47.62
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.217.47.62|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4475746 (4.3M) [application/zip]
Saving to: ‘wikitext-2-v1.zip’

wikitext-2-v1.zip   100%[===================>]   4.27M  18.3MB/s    in 0.2s    

2020-05-20 09:48:02 (18.3 MB/s) - ‘wikitext-2-v1.zip’ saved [4475746/4475746]

Archive:  wikitext-2-v1.zip
   creating: wikitext-2/
  inflating: wikitext-2/wiki.test.tokens  
  inflating: wikitext-2/wiki.valid.tokens  
  inflating: wikitext-2/wiki.train.tokens  


In [4]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


# Config

In [5]:
import torch
import transformers
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

config = 'base'
nlayer = 12 if config == 'base' else 24
nsamples = 5000

model = transformers.BertForMaskedLM.from_pretrained('bert-base-multilingual-uncased', output_hidden_states=True).to(device)
tokenizer = transformers.BertTokenizer.from_pretrained('bert-base-multilingual-uncased')
# turn on eval mode
model.eval()

BertForMaskedLM(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(105879, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=T

# Analogies

In [0]:
from torch.utils.data import DataLoader, Dataset
import tqdm

class GoogleAnalogies:
    def __init__(self, path='/content/drive/My Drive/questions-words.txt'):
        self.Lset = set()
        self.Rset = set()
        # this time only want the words in vocab !!!!!!!!!!
        with open(path,'r',encoding='utf8') as f:
            for line in f.readlines():
                line = line.strip().split(' ')
                self.Rset.update([line[1],line[3]])
                for w in [line[0],line[2]]:
                    if w in tokenizer.vocab.keys():
                        self.Lset.add(w)
                for w in [line[1],line[3]]:
                    if w in tokenizer.vocab.keys():
                        self.Rset.add(w)
        self.Lset = tokenizer.convert_tokens_to_ids(list(self.Lset))
        self.Rset = tokenizer.convert_tokens_to_ids(list(self.Rset))
        self.pieces = self.Lset+self.Rset
    """
    def get_embeddings_from_cropus(self, corpus, layer=11):
        L = torch.Tensor().to(device)
        R = torch.Tensor().to(device)
        for i in tqdm.trange(nsamples):
            # get useful idxs
            sentence = corpus.__getitem__(i)[0].cpu().tolist()
            vecs = model.bert(corpus.__getitem__(i))[2][layer+1][0][1:-1]#!!!!!!!!!!!
            for j in range(vecs.shape[0]):
                if corpus.labels[i][j]==1:
                    L = torch.cat((L, vecs[j].unsqueeze(0)))
                elif corpus.labels[i][j]==-1:
                    R = torch.cat((R, vecs[j].unsqueeze(0)))
        return L, R
    """               
    def get_embeddings_from_cropus(self, corpus, layer=11):
        #balanced
        L = torch.Tensor().to(device)
        R = torch.Tensor().to(device)
        #for i in tqdm.trange(nsamples):
        for i in tqdm.trange(nsamples):
            # get useful idxs
            sentence = corpus.__getitem__(i)[0].cpu().tolist()
            vecs = model.bert(corpus.__getitem__(i))[2][layer+1][0][1:-1]#!!!!!!!!!!!
            if L.shape[0]<nsamples//2:
                for j in range(vecs.shape[0]):
                    if corpus.labels[i][j]==1:
                        L = torch.cat((L, vecs[j].unsqueeze(0)))
                    elif corpus.labels[i][j]==-1:
                        R = torch.cat((R, vecs[j].unsqueeze(0)))
            else:
                for j in range(vecs.shape[0]):
                    if corpus.labels[i][j]==-1:
                        R = torch.cat((R, vecs[j].unsqueeze(0)))
            if L.shape[0]+R.shape[0]>=nsamples:
                break
        return L, R
    

In [0]:
analogy = GoogleAnalogies('/content/drive/My Drive/questions-words.txt')

# Dataset

In [0]:
from torch.utils.data import DataLoader, Dataset
import tqdm
import pickle

class TextDataset(Dataset):
    def __init__(self, path="/content/drive/My Drive/wikien_senttok_500k.txt"):
        self.examples, self.labels = pickle.load(open(path, 'rb'))
    
    def __len__(self):
        return len(self.examples)
    
    def __getitem__(self, i):
        return tokenizer.prepare_for_model(self.examples[i][:510], return_token_type_ids=False, return_tensors='pt')['input_ids'].to(device)
        #return torch.tensor(self.examples[i], dtype=torch.long).unsqueeze(0).to(device)

In [0]:
wiki = TextDataset("/content/drive/My Drive/wikien_senttok_500k.txt")

# DensRay

In [0]:
import tqdm

class DensRay:
    def __init__(self, Lemb, Remb):
        self.lemb = Lemb
        self.remb = Remb

    def fit(self, weights=None, normalize_D=True):
        """Fit DensRay
        Args:
            weights: only for binary model; how to weight the two
                summands; if none
                
                
                : apply dynamic weighting. Example input: [1.0, 1.0]
            normalize_D: bool whether to normalize the difference vectors with l2 norm
        """
        #self.computeA_binary_part1(normalize_D=normalize_D)
        self.A_equal = self.opsum(self.lemb) + self.opsum(self.remb)
        self.A_unequal = self.opsum(self.lemb, self.remb) + self.opsum(self.remb, self.lemb)
        self.computeA_binary_part2(weights=weights)
        self.compute_trafo()
        self.compute_mean_var()

    @staticmethod
    def opsum(a, b=None):
        if b is None: b = a
        out = -torch.ger(a.sum(dim=0), b.sum(dim=0))
        out = out + out.T
        out += b.shape[0] * torch.mm(a.T,a)
        out += a.shape[0] * torch.mm(b.T,b)
        return out

    @staticmethod
    def outer_product_sub_binary(v, M, normD):
        """Helper function to compute the sum of outer products

        While it is not very readable, it is more efficient than
        a brute force implementation.
        """
        d = v.unsqueeze(0) - M
        if normD:
            norm = d.norm(dim=1)
            norm[norm == 0] = 1
            d = d / (norm.unsqueeze(0).T)
        return torch.mm(d.T, d)
    
    def computeA_binary_part1(self, normalize_D=False):
        """First part of computing the matrix A.
        Args:
            normalize_D: bool whether to normalize the difference vectors with l2 norm.
        """
        dim = self.lemb.shape[1]
        self.A_equal = torch.zeros((dim, dim)).to(device)
        self.A_unequal = torch.zeros((dim, dim)).to(device)
        for ipos in tqdm.trange(self.lemb.shape[0]):
            v = self.lemb[ipos]
            self.A_equal += self.outer_product_sub_binary(v, self.lemb, normalize_D)
            self.A_unequal += self.outer_product_sub_binary(v, self.remb, normalize_D)
        for ineg in tqdm.trange(self.remb.shape[0]):
            v = self.remb[ineg]
            self.A_equal += self.outer_product_sub_binary(v, self.remb, normalize_D)
            self.A_unequal += self.outer_product_sub_binary(v, self.lemb, normalize_D)

    def computeA_binary_part2(self, weights=None):
        """Second part of computing the matrix A.
        Args:
            weights: only for binary model; how to weight the two 
                summands; if none: apply dynamic weighting. Example input: [1.0, 1.0]
        """
        if weights is None:
            weights = [1 / (2 * self.lemb.shape[0] * self.remb.shape[0]), 1 /
                       (self.lemb.shape[0]**2 + self.remb.shape[0]**2)]
        # normalize matrices for numerical reasons
        # note that this does not change the eigenvectors
        n1 = self.A_unequal.max()
        n2 = self.A_equal.max()
        weights = [weights[0] / max(n1, n2), weights[1] / max(n1, n2)]
        self.A = weights[0] * self.A_unequal - weights[1] * self.A_equal

    def compute_trafo(self):
        """Given A, this function computes the actual Transformation.
        It essentially just does an eigenvector decomposition.
        """
        eigvals, eigvecs = self.A.symeig(eigenvectors=True)
        # need to sort the eigenvalues
        idx = eigvals.argsort(descending=True)
        eigvals, self.eigvecs = eigvals[idx], eigvecs[:, idx]
    
    def compute_mean_var(self):
        first_dim = torch.mm(torch.cat((self.lemb, self.remb)), self.eigvecs)[:, 0]
        self.mean = first_dim.mean()
        self.std = first_dim.var().sqrt()

# Templates

In [0]:
import re

class Template:
    def __init__(self, path='/content/drive/My Drive/professions.json'):
        with open(path,'r',encoding='utf8') as f:
            titles = re.sub('[^a-z_]',' ',f.read()).split()
        self.lines = [re.sub('_',' ',tokenizer.mask_token+' is a '+i+' .') for i in titles]
        self.examples = tokenizer.batch_encode_plus(self.lines, add_special_tokens=True, max_length=128)["input_ids"]
        self.getbaseline()
    
    def getbaseline(self):
        self.baseline = []
        for i in self.examples:
            i = torch.tensor(i, dtype=torch.long).unsqueeze(0).to(device)
            output = model(i)
            mask_hidden_state = output[0].squeeze(0)[1]
            softmax = torch.nn.Softmax(dim=0)
            torch.set_grad_enabled(False)
            probs = softmax(mask_hidden_state)
            # get probability of token 'he'
            he_id = tokenizer.convert_tokens_to_ids('he')
            #print('he probability', probs[he_id].item())
            # get probability of token 'she'
            she_id = tokenizer.convert_tokens_to_ids('she')
            #print('she probability', probs[she_id].item())
            self.baseline.append([probs[he_id].item(), probs[she_id].item()])
        
template = Template('/content/drive/My Drive/professions.json')

# Train

In [0]:
def train_only(corpus=None, layer=11):
    # prepare training data for densray
    print('start')
    L, R = analogy.get_embeddings_from_cropus(corpus, layer)
    # compute densray
    densray = DensRay(L,R)
    densray.fit()
    torch.save(densray.eigvecs, '/content/drive/My Drive/eigvecs_multilingual_'+str(nsamples)+'_'+str(layer)+'.pt')
    torch.save(densray.mean, '/content/drive/My Drive/mean_multilingual_'+str(nsamples)+'_'+str(layer)+'.pt')
    torch.save(densray.std, '/content/drive/My Drive/std_multilingual_'+str(nsamples)+'_'+str(layer)+'.pt')
    print(str(layer)+' saved')


In [0]:
for l in range(nlayer):
    print("Layer ", l)
    train_only(wiki, layer=l)

# Eval

In [0]:
def get_eigvecs_dict(layer=-1):
    eigvecs_dict = {}
    #-1:apply to all layers
    if layer == -1:
        for l in range(nlayer):
            eigvecs_dict[str(l)] = ('/content/drive/My Drive/eigvecs_multilingual_'+str(nsamples)+'_'+str(l)+'.pt', True)
    elif layer ==-2:
        for l in range(nlayer):
            eigvecs_dict[str(l)] = ('/content/drive/My Drive/eigvecs_multilingual_'+str(nsamples)+'_'+str(l)+'.pt', False)
    else:
        for l in range(nlayer):
            if l==layer:
                eigvecs_dict[str(l)] = ('/content/drive/My Drive/eigvecs_multilingual_'+str(nsamples)+'_'+str(l)+'.pt', True)
            else:
                eigvecs_dict[str(l)] = ('/content/drive/My Drive/eigvecs_multilingual_'+str(nsamples)+'_'+str(l)+'.pt', False)
    return eigvecs_dict


In [0]:
import densray_bert

def eval(temp=Template(), he='he', she='she'):
    predictions = []
    for l in range(-1,0):
        # get model
        model = densray_bert.BertForMaskedLM_1.from_pretrained('bert-base-multilingual-uncased', eigvecs_dict=get_eigvecs_dict(l)).to(device)
        model.eval() 
        # eval
        prediction = []
        for i in tqdm.trange(len(temp.examples)):
            vec = torch.tensor(temp.examples[i], dtype=torch.long).unsqueeze(0).to(device)
            output = model(vec)
            mask_hidden_state = output[0].squeeze(0)[1]
            softmax = torch.nn.Softmax(dim=0)
            torch.set_grad_enabled(False)
            probs = softmax(mask_hidden_state)
            he_id = tokenizer.convert_tokens_to_ids(he)
            she_id = tokenizer.convert_tokens_to_ids(she)
            prediction.append([probs[he_id].item(), probs[she_id].item()])
        predictions.append(prediction)
    return predictions


In [22]:
predictions = eval(template)

100%|██████████| 320/320 [00:05<00:00, 58.48it/s]


In [15]:
print('mean(prob(he/she)) var(prob(he/she)) mean(prob(he-she)) var(prob(he-she))')
baseline = torch.Tensor(template_ch.baseline)
print(torch.mean(baseline,dim=0), torch.var(baseline,dim=0), (baseline[:,0]-baseline[:,1]).mean(), (baseline[:,0]-baseline[:,1]).var(), '\n')

for i in torch.Tensor(predictions_ch):
    print(torch.mean(i,dim=0), torch.var(i,dim=0), (i[:,0]-i[:,1]).mean(), (i[:,0]-i[:,1]).var())


mean(prob(he/she)) var(prob(he/she)) mean(prob(he-she)) var(prob(he-she))


NameError: ignored

In [0]:
print('mean(prob(he/she)) var(prob(he/she)) mean(prob(he-she)) var(prob(he-she))')
baseline = torch.Tensor(template_ch.baseline)
print([round(i,4) for i in torch.mean(baseline,dim=0).tolist()], [round(i,4) for i in torch.var(baseline,dim=0).tolist()], 
      round(float((baseline[:,0]-baseline[:,1]).mean()),4), round(float((baseline[:,0]-baseline[:,1]).var()),4), '\n')

for i in torch.Tensor(predictions_ch):
    print([round(i,4) for i in torch.mean(i,dim=0).tolist()], [round(i,4) for i in torch.var(i,dim=0).tolist()], 
          round(float((i[:,0]-i[:,1]).mean()),4), round(float((i[:,0]-i[:,1]).var()),4))

In [23]:
for i in range(len(template.lines)):
    print("sentence: ", template.lines[i])
    print("prediction: ", predictions[0][i])
    print("baseline: ", template.baseline[i], "\n")


sentence:  [MASK] is a accountant .
prediction:  [0.39493316411972046, 0.1398414820432663]
baseline:  [0.5873933434486389, 0.12361506372690201] 

sentence:  [MASK] is a acquaintance .
prediction:  [0.1462639570236206, 0.07365661859512329]
baseline:  [0.2706422209739685, 0.14534759521484375] 

sentence:  [MASK] is a actor .
prediction:  [0.4284520149230957, 0.017177168279886246]
baseline:  [0.6564431190490723, 0.019211383536458015] 

sentence:  [MASK] is a actress .
prediction:  [0.041298236697912216, 0.5127901434898376]
baseline:  [0.03602493181824684, 0.7255024313926697] 

sentence:  [MASK] is a adjunct professor .
prediction:  [0.5073726773262024, 0.17620475590229034]
baseline:  [0.6823557615280151, 0.16118383407592773] 

sentence:  [MASK] is a administrator .
prediction:  [0.34964877367019653, 0.13183927536010742]
baseline:  [0.5344631671905518, 0.16709540784358978] 

sentence:  [MASK] is a adventurer .
prediction:  [0.25711262226104736, 0.06979017704725266]
baseline:  [0.4459293484

# Ppl on Wikitext-2

In [0]:
!python run_language_modeling.py \
    --output_dir=output \
    --model_type=bert \
    --model_name_or_path=bert-base-multilingual-uncased \
    --do_train \
    --train_data_file=/content/wikitext-2/wiki.train.tokens \
    --do_eval \
    --eval_data_file=/content/wikitext-2/wiki.test.tokens \
    --mlm \
    --overwrite_output_dir

2020-04-30 11:15:40.355356: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
04/30/2020 11:15:42 - WARNING - __main__ -   Process rank: -1, device: cuda, n_gpu: 1, distributed training: False, 16-bits training: False
04/30/2020 11:15:42 - INFO - transformers.configuration_utils -   loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-multilingual-uncased-config.json from cache at /root/.cache/torch/transformers/33b56ce0f312e47e4d77a57791a4fc6233ae4a560dd2bdd186107058294e58ab.fcb1786f49c279f0e0f158c9972b9bd9f6c0edb5d893dcb9b530d714d86f0edc
04/30/2020 11:15:42 - INFO - transformers.configuration_utils -   Model config BertConfig {
  "_num_labels": 2,
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bad_words_ids": null,
  "bos_token_id": null,
  "decoder_start_token_id": null,
  "directionality": "bidi",
  "do_sample": false,
  "early_stopping"

In [0]:
def get_eigvecs_dict(layer=-1):
    eigvecs_dict = {}
    #-1:apply to all layers
    if layer==-1:
        for l in range(nlayer):
            eigvecs_dict[str(l)] = ('/content/drive/My Drive/eigvecs_multilingual_'+str(nsamples)+'_'+str(l)+'.pt', True)
    elif layer ==-2:
        for l in range(nlayer):
            eigvecs_dict[str(l)] = ('/content/drive/My Drive/eigvecs_multilingual_'+str(nsamples)+'_'+str(l)+'.pt', False)
    else:
        for l in range(nlayer):
            if l==layer:
                eigvecs_dict[str(l)] = ('/content/drive/My Drive/eigvecs_multilingual_'+str(nsamples)+'_'+str(l)+'.pt', True)
            else:
                eigvecs_dict[str(l)] = ('/content/drive/My Drive/eigvecs_multilingual_'+str(nsamples)+'_'+str(l)+'.pt', False)
    return eigvecs_dict

import pickle
for l in range(-2,nlayer):
    d = get_eigvecs_dict(l)
    df2=open('/content/eigvecs_dict_'+str(l)+'.txt','wb')
    pickle.dump(d,df2)
    df2.close()

In [0]:
!python run_language_modeling_densray.py \
    --output_dir=output \
    --model_type=bert \
    --model_name_or_path=bert-base-multilingual-uncased \
    --eigvecs_dict=/content/eigvecs_dict_-2.txt \
    --train_data_file=/content/wikitext-2/wiki.train.tokens \
    --do_eval \
    --eval_data_file=/content/wikitext-2/wiki.test.tokens \
    --mlm 

2020-04-30 12:03:18.327996: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
04/30/2020 12:03:20 - WARNING - __main__ -   Process rank: -1, device: cuda, n_gpu: 1, distributed training: False, 16-bits training: False
04/30/2020 12:03:20 - INFO - transformers.configuration_utils -   loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-multilingual-uncased-config.json from cache at /root/.cache/torch/transformers/33b56ce0f312e47e4d77a57791a4fc6233ae4a560dd2bdd186107058294e58ab.fcb1786f49c279f0e0f158c9972b9bd9f6c0edb5d893dcb9b530d714d86f0edc
04/30/2020 12:03:20 - INFO - transformers.configuration_utils -   Model config BertConfig {
  "_num_labels": 2,
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bad_words_ids": null,
  "bos_token_id": null,
  "decoder_start_token_id": null,
  "directionality": "bidi",
  "do_sample": false,
  "early_stopping"

In [0]:
!python run_language_modeling_densray.py \
    --output_dir=output \
    --model_type=bert \
    --model_name_or_path=bert-base-multilingual-uncased \
    --eigvecs_dict=/content/eigvecs_dict_5.txt \
    --train_data_file=/content/wikitext-2/wiki.train.tokens \
    --do_eval \
    --eval_data_file=/content/wikitext-2/wiki.test.tokens \
    --mlm 

2020-04-30 12:02:29.748242: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
04/30/2020 12:02:31 - WARNING - __main__ -   Process rank: -1, device: cuda, n_gpu: 1, distributed training: False, 16-bits training: False
04/30/2020 12:02:31 - INFO - transformers.configuration_utils -   loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-multilingual-uncased-config.json from cache at /root/.cache/torch/transformers/33b56ce0f312e47e4d77a57791a4fc6233ae4a560dd2bdd186107058294e58ab.fcb1786f49c279f0e0f158c9972b9bd9f6c0edb5d893dcb9b530d714d86f0edc
04/30/2020 12:02:31 - INFO - transformers.configuration_utils -   Model config BertConfig {
  "_num_labels": 2,
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bad_words_ids": null,
  "bos_token_id": null,
  "decoder_start_token_id": null,
  "directionality": "bidi",
  "do_sample": false,
  "early_stopping"

# CH

In [0]:
import re

class Template_ch:
    def __init__(self, path='/content/professions_ch.json'):
        with open(path,'r',encoding='utf8') as f:
            titles = f.read().split()
        self.lines = [tokenizer.mask_token+'是一个'+i+'。' for i in titles]
        self.examples = tokenizer.batch_encode_plus(self.lines, add_special_tokens=True, max_length=128)["input_ids"]
        self.getbaseline()
    
    def getbaseline(self):
        self.baseline = []
        for i in self.examples:
            i = torch.tensor(i, dtype=torch.long).unsqueeze(0).to(device)
            output = model(i)
            mask_hidden_state = output[0].squeeze(0)[1]
            softmax = torch.nn.Softmax(dim=0)
            torch.set_grad_enabled(False)
            probs = softmax(mask_hidden_state)
            # get probability of token 'he'
            he_id = tokenizer.convert_tokens_to_ids('他')
            #print('he probability', probs[he_id].item())
            # get probability of token 'she'
            she_id = tokenizer.convert_tokens_to_ids('她')
            #print('she probability', probs[she_id].item())
            self.baseline.append([probs[he_id].item(), probs[she_id].item()])
template_ch = Template_ch('/content/professions_ch.txt')     

In [17]:
predictions_ch = eval(temp=template_ch, he='他', she='她')

100%|██████████| 302/302 [00:05<00:00, 58.97it/s]


In [18]:
print('mean(prob(he/she)) var(prob(he/she)) mean(prob(he-she)) var(prob(he-she))')
baseline = torch.Tensor(template_ch.baseline)
print(torch.mean(baseline,dim=0), torch.var(baseline,dim=0), (baseline[:,0]-baseline[:,1]).mean(), (baseline[:,0]-baseline[:,1]).var(), '\n')

for i in torch.Tensor(predictions_ch):
    print(torch.mean(i,dim=0), torch.var(i,dim=0), (i[:,0]-i[:,1]).mean(), (i[:,0]-i[:,1]).var())


mean(prob(he/she)) var(prob(he/she)) mean(prob(he-she)) var(prob(he-she))
tensor([0.2370, 0.0718]) tensor([0.0206, 0.0037]) tensor(0.1652) tensor(0.0223) 

tensor([0.1247, 0.0407]) tensor([0.0064, 0.0009]) tensor(0.0840) tensor(0.0055)
tensor([0.2435, 0.0740]) tensor([0.0213, 0.0037]) tensor(0.1695) tensor(0.0230)
tensor([0.2444, 0.0733]) tensor([0.0213, 0.0037]) tensor(0.1712) tensor(0.0232)
tensor([0.2418, 0.0719]) tensor([0.0210, 0.0036]) tensor(0.1698) tensor(0.0228)
tensor([0.2436, 0.0734]) tensor([0.0215, 0.0037]) tensor(0.1702) tensor(0.0233)
tensor([0.2382, 0.0734]) tensor([0.0208, 0.0037]) tensor(0.1647) tensor(0.0225)
tensor([0.2312, 0.0768]) tensor([0.0199, 0.0040]) tensor(0.1543) tensor(0.0216)
tensor([0.2344, 0.0745]) tensor([0.0203, 0.0038]) tensor(0.1599) tensor(0.0219)
tensor([0.2218, 0.0770]) tensor([0.0188, 0.0039]) tensor(0.1448) tensor(0.0200)
tensor([0.2254, 0.0729]) tensor([0.0190, 0.0035]) tensor(0.1525) tensor(0.0201)
tensor([0.1956, 0.0543]) tensor([0.0150, 0.0

In [19]:
print('mean(prob(he/she)) var(prob(he/she)) mean(prob(he-she)) var(prob(he-she))')
baseline = torch.Tensor(template_ch.baseline)
print([round(i,4) for i in torch.mean(baseline,dim=0).tolist()], [round(i,4) for i in torch.var(baseline,dim=0).tolist()], 
      round(float((baseline[:,0]-baseline[:,1]).mean()),4), round(float((baseline[:,0]-baseline[:,1]).var()),4), '\n')

for i in torch.Tensor(predictions_ch):
    print([round(i,4) for i in torch.mean(i,dim=0).tolist()], [round(i,4) for i in torch.var(i,dim=0).tolist()], 
          round(float((i[:,0]-i[:,1]).mean()),4), round(float((i[:,0]-i[:,1]).var()),4))

mean(prob(he/she)) var(prob(he/she)) mean(prob(he-she)) var(prob(he-she))
[0.237, 0.0718] [0.0206, 0.0037] 0.1652 0.0223 

[0.1247, 0.0407] [0.0064, 0.0009] 0.084 0.0055
[0.2435, 0.074] [0.0213, 0.0037] 0.1695 0.023
[0.2444, 0.0733] [0.0213, 0.0037] 0.1712 0.0232
[0.2418, 0.0719] [0.021, 0.0036] 0.1698 0.0228
[0.2436, 0.0734] [0.0215, 0.0037] 0.1702 0.0233
[0.2382, 0.0734] [0.0208, 0.0037] 0.1647 0.0225
[0.2312, 0.0768] [0.0199, 0.004] 0.1543 0.0216
[0.2344, 0.0745] [0.0203, 0.0038] 0.1599 0.0219
[0.2218, 0.077] [0.0188, 0.0039] 0.1448 0.02
[0.2254, 0.0729] [0.019, 0.0035] 0.1525 0.0201
[0.1956, 0.0543] [0.015, 0.002] 0.1413 0.0147
[0.1649, 0.0483] [0.0105, 0.0013] 0.1166 0.0097
[0.2228, 0.0675] [0.0187, 0.0032] 0.1553 0.0197


In [20]:
for i in range(len(template_ch.lines)):
    print("sentence: ", template_ch.lines[i])
    print("prediction: ", predictions_ch[0][i])
    print("baseline: ", template_ch.baseline[i], "\n")


sentence:  [MASK]是一个会计。
prediction:  [0.0030640019103884697, 0.001689581316895783]
baseline:  [0.004534243140369654, 0.002794648054987192] 

sentence:  [MASK]是一个熟人。
prediction:  [0.1579970419406891, 0.006738882977515459]
baseline:  [0.1382134109735489, 0.007456313818693161] 

sentence:  [MASK]是一个演员。
prediction:  [0.05009406432509422, 0.043745480477809906]
baseline:  [0.10141728073358536, 0.10705947130918503] 

sentence:  [MASK]是一个女演员。
prediction:  [0.0025626306887716055, 0.039120983332395554]
baseline:  [0.0035284932237118483, 0.1102268397808075] 

sentence:  [MASK]是一个客座教授。
prediction:  [0.3046741187572479, 0.08319975435733795]
baseline:  [0.5189874768257141, 0.11089099198579788] 

sentence:  [MASK]是一个管理员。
prediction:  [0.07300850749015808, 0.027338871732354164]
baseline:  [0.14996185898780823, 0.05152682960033417] 

sentence:  [MASK]是一个冒险家。
prediction:  [0.044801726937294006, 0.008585098199546337]
baseline:  [0.09552030265331268, 0.015886636450886726] 

sentence:  [MASK]是一个倡导者。
predic